name: Test, Build, and Deploy with GameCI

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

on:
  push:
    branches:
      - master
    paths:
      - "Assets/**"
      - "Packages/**"
      - "ProjectSettings/**"
  pull_request:
    branches:
      - master
    paths:
      - "Assets/**"
      - "Packages/**"
      - "ProjectSettings/**"

jobs:
  build:
    name: Build for Androind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build artifacs
        uses: game-ci/unity-builder@v2
        with:
          targetPlatform: Android

      - name: Upload artifacs
        uses: actions/upload-artifact@v2
        with:
          name: build-Android
          path: build/Android
